[2025-03-27T06:40:29.291+0000] {processor.py:156} INFO - Started process (PID=392) to work on /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T06:40:29.293+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/data_ingestion_gcs_dag.py for tasks to queue
[2025-03-27T06:40:29.295+0000] {logging_mixin.py:117} INFO - [2025-03-27T06:40:29.295+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T06:40:33.699+0000] {processor.py:768} INFO - DAG(s) dict_keys(['data_ingestion_gcs_dag']) retrieved from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T06:40:34.077+0000] {logging_mixin.py:117} INFO - [2025-03-27T06:40:34.077+0000] {manager.py:508} INFO - Created Permission View: can delete on DAG:data_ingestion_gcs_dag
[2025-03-27T06:40:34.093+0000] {logging_mixin.py:117} INFO - [2025-03-27T06:40:34.092+0000] {manager.py:508} INFO - Created Permission View: can read on DAG:data_ingestion_gcs_dag
[2025-03-27T06:40:34.104+0000] {logging_mixin.py:117} INFO - [2025-03-27T06:40:34.104+0000] {manager.py:508} INFO - Created Permission View: can edit on DAG:data_ingestion_gcs_dag
[2025-03-27T06:40:34.105+0000] {logging_mixin.py:117} INFO - [2025-03-27T06:40:34.105+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2025-03-27T06:40:34.123+0000] {logging_mixin.py:117} INFO - [2025-03-27T06:40:34.122+0000] {dag.py:2594} INFO - Creating ORM DAG for data_ingestion_gcs_dag
[2025-03-27T06:40:34.140+0000] {logging_mixin.py:117} INFO - [2025-03-27T06:40:34.140+0000] {dag.py:3324} INFO - Setting next_dagrun for data_ingestion_gcs_dag to 2025-03-26T00:00:00+00:00, run_after=2025-03-27T00:00:00+00:00
[2025-03-27T06:40:34.173+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/data_ingestion_gcs_dag.py took 4.888 seconds
[2025-03-27T06:41:04.541+0000] {processor.py:156} INFO - Started process (PID=415) to work on /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T06:41:04.543+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/data_ingestion_gcs_dag.py for tasks to queue
[2025-03-27T06:41:04.544+0000] {logging_mixin.py:117} INFO - [2025-03-27T06:41:04.544+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T06:41:05.866+0000] {processor.py:768} INFO - DAG(s) dict_keys(['data_ingestion_gcs_dag']) retrieved from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T06:41:05.919+0000] {logging_mixin.py:117} INFO - [2025-03-27T06:41:05.919+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2025-03-27T06:41:05.970+0000] {logging_mixin.py:117} INFO - [2025-03-27T06:41:05.969+0000] {dag.py:3324} INFO - Setting next_dagrun for data_ingestion_gcs_dag to 2025-03-26T00:00:00+00:00, run_after=2025-03-27T00:00:00+00:00
[2025-03-27T06:41:05.999+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/data_ingestion_gcs_dag.py took 1.462 seconds
[2025-03-27T06:41:10.668+0000] {processor.py:156} INFO - Started process (PID=424) to work on /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T06:41:10.671+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/data_ingestion_gcs_dag.py for tasks to queue
[2025-03-27T06:41:10.673+0000] {logging_mixin.py:117} INFO - [2025-03-27T06:41:10.673+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T06:41:11.906+0000] {logging_mixin.py:117} INFO - [2025-03-27T06:41:11.899+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_gcs_dag.py", line 90, in <module>
    "object_name": f"raw/{parquet_file}",
NameError: name 'parquet_file' is not defined
[2025-03-27T06:41:11.909+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T06:41:11.934+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/data_ingestion_gcs_dag.py took 1.275 seconds
[2025-03-27T06:41:42.236+0000] {processor.py:156} INFO - Started process (PID=442) to work on /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T06:41:42.239+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/data_ingestion_gcs_dag.py for tasks to queue
[2025-03-27T06:41:42.241+0000] {logging_mixin.py:117} INFO - [2025-03-27T06:41:42.241+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T06:41:43.501+0000] {logging_mixin.py:117} INFO - [2025-03-27T06:41:43.465+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_gcs_dag.py", line 90, in <module>
    "bucket": BUCKET,
NameError: name 'parquet_file' is not defined
[2025-03-27T06:41:43.503+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T06:41:43.559+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/data_ingestion_gcs_dag.py took 1.330 seconds
[2025-03-27T06:42:13.908+0000] {processor.py:156} INFO - Started process (PID=466) to work on /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T06:42:13.911+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/data_ingestion_gcs_dag.py for tasks to queue
[2025-03-27T06:42:13.913+0000] {logging_mixin.py:117} INFO - [2025-03-27T06:42:13.913+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T06:42:15.401+0000] {logging_mixin.py:117} INFO - [2025-03-27T06:42:15.394+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_gcs_dag.py", line 19, in <module>
    dataset_url = f"https://raw.githubusercontent.com/tategallery/collection/refs/heads/master/{dataset_file}"
NameError: name 'dataset_file' is not defined
[2025-03-27T06:42:15.403+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T06:42:15.433+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/data_ingestion_gcs_dag.py took 1.532 seconds
[2025-03-27T06:42:21.550+0000] {processor.py:156} INFO - Started process (PID=475) to work on /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T06:42:21.552+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/data_ingestion_gcs_dag.py for tasks to queue
[2025-03-27T06:42:21.554+0000] {logging_mixin.py:117} INFO - [2025-03-27T06:42:21.553+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T06:42:22.601+0000] {logging_mixin.py:117} INFO - [2025-03-27T06:42:22.593+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_gcs_dag.py", line 75, in <module>
    bash_command=f"curl -sSL {dataset_url} > {path_to_local_home}/{dataset_file}"
NameError: name 'dataset_url' is not defined
[2025-03-27T06:42:22.603+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T06:42:22.630+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/data_ingestion_gcs_dag.py took 1.086 seconds
[2025-03-27T06:42:52.881+0000] {processor.py:156} INFO - Started process (PID=491) to work on /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T06:42:52.882+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/data_ingestion_gcs_dag.py for tasks to queue
[2025-03-27T06:42:52.883+0000] {logging_mixin.py:117} INFO - [2025-03-27T06:42:52.883+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T06:42:53.839+0000] {logging_mixin.py:117} INFO - [2025-03-27T06:42:53.832+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_gcs_dag.py", line 75, in <module>
    bash_command=f"curl -sSL {dataset_url} > {path_to_local_home}/{dataset_file}"
NameError: name 'dataset_url' is not defined
[2025-03-27T06:42:53.841+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T06:42:53.885+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/data_ingestion_gcs_dag.py took 1.008 seconds
[2025-03-27T06:43:24.211+0000] {processor.py:156} INFO - Started process (PID=514) to work on /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T06:43:24.213+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/data_ingestion_gcs_dag.py for tasks to queue
[2025-03-27T06:43:24.214+0000] {logging_mixin.py:117} INFO - [2025-03-27T06:43:24.214+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T06:43:25.412+0000] {logging_mixin.py:117} INFO - [2025-03-27T06:43:25.404+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_gcs_dag.py", line 75, in <module>
    bash_command=f"curl -sSL {dataset_url} > {path_to_local_home}/{dataset_file}"
NameError: name 'dataset_url' is not defined
[2025-03-27T06:43:25.415+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T06:43:25.444+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/data_ingestion_gcs_dag.py took 1.238 seconds
[2025-03-27T06:43:55.793+0000] {processor.py:156} INFO - Started process (PID=537) to work on /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T06:43:55.795+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/data_ingestion_gcs_dag.py for tasks to queue
[2025-03-27T06:43:55.796+0000] {logging_mixin.py:117} INFO - [2025-03-27T06:43:55.796+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T06:43:57.118+0000] {logging_mixin.py:117} INFO - [2025-03-27T06:43:57.110+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_gcs_dag.py", line 75, in <module>
    bash_command=f"curl -sSL {dataset_url} > {path_to_local_home}/{dataset_file}"
NameError: name 'dataset_url' is not defined
[2025-03-27T06:43:57.120+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T06:43:57.152+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/data_ingestion_gcs_dag.py took 1.364 seconds
[2025-03-27T06:44:01.840+0000] {processor.py:156} INFO - Started process (PID=539) to work on /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T06:44:01.842+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/data_ingestion_gcs_dag.py for tasks to queue
[2025-03-27T06:44:01.843+0000] {logging_mixin.py:117} INFO - [2025-03-27T06:44:01.843+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T06:44:02.987+0000] {logging_mixin.py:117} INFO - [2025-03-27T06:44:02.981+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_gcs_dag.py", line 67, in <module>
    bash_command=f"curl -sSL {dataset_url} > {path_to_local_home}/{dataset_file}"
NameError: name 'dataset_url' is not defined
[2025-03-27T06:44:02.990+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T06:44:03.029+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/data_ingestion_gcs_dag.py took 1.193 seconds
[2025-03-27T06:44:33.111+0000] {processor.py:156} INFO - Started process (PID=562) to work on /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T06:44:33.112+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/data_ingestion_gcs_dag.py for tasks to queue
[2025-03-27T06:44:33.114+0000] {logging_mixin.py:117} INFO - [2025-03-27T06:44:33.113+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T06:44:34.264+0000] {logging_mixin.py:117} INFO - [2025-03-27T06:44:34.257+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_gcs_dag.py", line 67, in <module>
    bash_command=f"curl -sSL {dataset_url} > {path_to_local_home}/{dataset_file}"
NameError: name 'dataset_url' is not defined
[2025-03-27T06:44:34.267+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T06:44:34.306+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/data_ingestion_gcs_dag.py took 1.201 seconds
[2025-03-27T06:45:04.600+0000] {processor.py:156} INFO - Started process (PID=578) to work on /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T06:45:04.602+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/data_ingestion_gcs_dag.py for tasks to queue
[2025-03-27T06:45:04.603+0000] {logging_mixin.py:117} INFO - [2025-03-27T06:45:04.603+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T06:45:05.770+0000] {logging_mixin.py:117} INFO - [2025-03-27T06:45:05.762+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_gcs_dag.py", line 67, in <module>
    bash_command=f"curl -sSL {dataset_url} > {path_to_local_home}/{dataset_file}"
NameError: name 'dataset_url' is not defined
[2025-03-27T06:45:05.772+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T06:45:05.818+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/data_ingestion_gcs_dag.py took 1.223 seconds
[2025-03-27T06:45:35.913+0000] {processor.py:156} INFO - Started process (PID=601) to work on /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T06:45:35.915+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/data_ingestion_gcs_dag.py for tasks to queue
[2025-03-27T06:45:35.916+0000] {logging_mixin.py:117} INFO - [2025-03-27T06:45:35.916+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T06:45:36.997+0000] {logging_mixin.py:117} INFO - [2025-03-27T06:45:36.990+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_gcs_dag.py", line 67, in <module>
    bash_command=f"curl -sSL {dataset_url} > {path_to_local_home}/{dataset_file}"
NameError: name 'dataset_url' is not defined
[2025-03-27T06:45:37.000+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T06:45:37.043+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/data_ingestion_gcs_dag.py took 1.134 seconds
[2025-03-27T06:46:07.188+0000] {processor.py:156} INFO - Started process (PID=624) to work on /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T06:46:07.190+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/data_ingestion_gcs_dag.py for tasks to queue
[2025-03-27T06:46:07.191+0000] {logging_mixin.py:117} INFO - [2025-03-27T06:46:07.191+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T06:46:08.518+0000] {logging_mixin.py:117} INFO - [2025-03-27T06:46:08.510+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_gcs_dag.py", line 67, in <module>
    bash_command=f"curl -sSL {dataset_url} > {path_to_local_home}/{dataset_file}"
NameError: name 'dataset_url' is not defined
[2025-03-27T06:46:08.520+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T06:46:08.570+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/data_ingestion_gcs_dag.py took 1.387 seconds
[2025-03-27T06:46:38.902+0000] {processor.py:156} INFO - Started process (PID=640) to work on /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T06:46:38.904+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/data_ingestion_gcs_dag.py for tasks to queue
[2025-03-27T06:46:38.905+0000] {logging_mixin.py:117} INFO - [2025-03-27T06:46:38.905+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T06:46:40.078+0000] {logging_mixin.py:117} INFO - [2025-03-27T06:46:40.070+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_gcs_dag.py", line 67, in <module>
    bash_command=f"curl -sSL {dataset_url} > {path_to_local_home}/{dataset_file}"
NameError: name 'dataset_url' is not defined
[2025-03-27T06:46:40.080+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T06:46:40.122+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/data_ingestion_gcs_dag.py took 1.227 seconds
[2025-03-27T06:47:08.180+0000] {processor.py:156} INFO - Started process (PID=663) to work on /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T06:47:08.182+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/data_ingestion_gcs_dag.py for tasks to queue
[2025-03-27T06:47:08.184+0000] {logging_mixin.py:117} INFO - [2025-03-27T06:47:08.184+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T06:47:09.322+0000] {logging_mixin.py:117} INFO - [2025-03-27T06:47:09.312+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_gcs_dag.py", line 74, in <module>
    python_callable=format_to_parquet,
NameError: name 'format_to_parquet' is not defined
[2025-03-27T06:47:09.325+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T06:47:09.376+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/data_ingestion_gcs_dag.py took 1.203 seconds
[2025-03-27T06:47:39.702+0000] {processor.py:156} INFO - Started process (PID=679) to work on /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T06:47:39.703+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/data_ingestion_gcs_dag.py for tasks to queue
[2025-03-27T06:47:39.705+0000] {logging_mixin.py:117} INFO - [2025-03-27T06:47:39.704+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T06:47:40.685+0000] {logging_mixin.py:117} INFO - [2025-03-27T06:47:40.677+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_gcs_dag.py", line 74, in <module>
    python_callable=format_to_parquet,
NameError: name 'format_to_parquet' is not defined
[2025-03-27T06:47:40.690+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T06:47:40.742+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/data_ingestion_gcs_dag.py took 1.043 seconds
[2025-03-27T06:48:11.012+0000] {processor.py:156} INFO - Started process (PID=702) to work on /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T06:48:11.014+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/data_ingestion_gcs_dag.py for tasks to queue
[2025-03-27T06:48:11.016+0000] {logging_mixin.py:117} INFO - [2025-03-27T06:48:11.015+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T06:48:12.099+0000] {logging_mixin.py:117} INFO - [2025-03-27T06:48:12.091+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_gcs_dag.py", line 74, in <module>
    python_callable=format_to_parquet,
NameError: name 'format_to_parquet' is not defined
[2025-03-27T06:48:12.101+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T06:48:12.150+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/data_ingestion_gcs_dag.py took 1.144 seconds
[2025-03-27T06:48:42.362+0000] {processor.py:156} INFO - Started process (PID=719) to work on /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T06:48:42.366+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/data_ingestion_gcs_dag.py for tasks to queue
[2025-03-27T06:48:42.369+0000] {logging_mixin.py:117} INFO - [2025-03-27T06:48:42.368+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T06:48:43.817+0000] {logging_mixin.py:117} INFO - [2025-03-27T06:48:43.810+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_gcs_dag.py", line 74, in <module>
    python_callable=format_to_parquet,
NameError: name 'format_to_parquet' is not defined
[2025-03-27T06:48:43.820+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T06:48:43.864+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/data_ingestion_gcs_dag.py took 1.509 seconds
[2025-03-27T06:49:14.205+0000] {processor.py:156} INFO - Started process (PID=742) to work on /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T06:49:14.207+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/data_ingestion_gcs_dag.py for tasks to queue
[2025-03-27T06:49:14.208+0000] {logging_mixin.py:117} INFO - [2025-03-27T06:49:14.208+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T06:49:15.207+0000] {logging_mixin.py:117} INFO - [2025-03-27T06:49:15.199+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_gcs_dag.py", line 74, in <module>
    python_callable=format_to_parquet,
NameError: name 'format_to_parquet' is not defined
[2025-03-27T06:49:15.209+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T06:49:15.249+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/data_ingestion_gcs_dag.py took 1.048 seconds
[2025-03-27T06:49:45.485+0000] {processor.py:156} INFO - Started process (PID=765) to work on /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T06:49:45.487+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/data_ingestion_gcs_dag.py for tasks to queue
[2025-03-27T06:49:45.488+0000] {logging_mixin.py:117} INFO - [2025-03-27T06:49:45.488+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T06:49:46.640+0000] {logging_mixin.py:117} INFO - [2025-03-27T06:49:46.633+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_gcs_dag.py", line 74, in <module>
    python_callable=format_to_parquet,
NameError: name 'format_to_parquet' is not defined
[2025-03-27T06:49:46.642+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T06:49:46.688+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/data_ingestion_gcs_dag.py took 1.208 seconds
[2025-03-27T06:50:16.837+0000] {processor.py:156} INFO - Started process (PID=781) to work on /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T06:50:16.839+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/data_ingestion_gcs_dag.py for tasks to queue
[2025-03-27T06:50:16.840+0000] {logging_mixin.py:117} INFO - [2025-03-27T06:50:16.840+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T06:50:18.004+0000] {logging_mixin.py:117} INFO - [2025-03-27T06:50:17.991+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_gcs_dag.py", line 74, in <module>
    python_callable=format_to_parquet,
NameError: name 'format_to_parquet' is not defined
[2025-03-27T06:50:18.009+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T06:50:18.055+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/data_ingestion_gcs_dag.py took 1.223 seconds
[2025-03-27T06:50:47.301+0000] {processor.py:156} INFO - Started process (PID=804) to work on /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T06:50:47.303+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/data_ingestion_gcs_dag.py for tasks to queue
[2025-03-27T06:50:47.304+0000] {logging_mixin.py:117} INFO - [2025-03-27T06:50:47.304+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T06:50:48.473+0000] {logging_mixin.py:117} INFO - [2025-03-27T06:50:48.465+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_gcs_dag.py", line 104, in <module>
    "sourceUris": [f"gs://{BUCKET}/raw/{parquet_file}"],
NameError: name 'parquet_file' is not defined
[2025-03-27T06:50:48.475+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T06:50:48.499+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/data_ingestion_gcs_dag.py took 1.203 seconds
[2025-03-27T06:51:18.618+0000] {processor.py:156} INFO - Started process (PID=828) to work on /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T06:51:18.621+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/data_ingestion_gcs_dag.py for tasks to queue
[2025-03-27T06:51:18.622+0000] {logging_mixin.py:117} INFO - [2025-03-27T06:51:18.622+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T06:51:19.871+0000] {logging_mixin.py:117} INFO - [2025-03-27T06:51:19.864+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_gcs_dag.py", line 104, in <module>
    "sourceUris": [f"gs://{BUCKET}/raw/{parquet_file}"],
NameError: name 'parquet_file' is not defined
[2025-03-27T06:51:19.873+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T06:51:19.915+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/data_ingestion_gcs_dag.py took 1.305 seconds
[2025-03-27T06:51:50.117+0000] {processor.py:156} INFO - Started process (PID=845) to work on /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T06:51:50.119+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/data_ingestion_gcs_dag.py for tasks to queue
[2025-03-27T06:51:50.121+0000] {logging_mixin.py:117} INFO - [2025-03-27T06:51:50.120+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T06:51:51.552+0000] {logging_mixin.py:117} INFO - [2025-03-27T06:51:51.543+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_gcs_dag.py", line 104, in <module>
    "sourceUris": [f"gs://{BUCKET}/raw/{parquet_file}"],
NameError: name 'parquet_file' is not defined
[2025-03-27T06:51:51.555+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T06:51:51.602+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/data_ingestion_gcs_dag.py took 1.498 seconds
[2025-03-27T06:52:21.968+0000] {processor.py:156} INFO - Started process (PID=866) to work on /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T06:52:21.969+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/data_ingestion_gcs_dag.py for tasks to queue
[2025-03-27T06:52:21.971+0000] {logging_mixin.py:117} INFO - [2025-03-27T06:52:21.970+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T06:52:23.073+0000] {logging_mixin.py:117} INFO - [2025-03-27T06:52:23.066+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_gcs_dag.py", line 104, in <module>
    "sourceUris": [f"gs://{BUCKET}/raw/{parquet_file}"],
NameError: name 'parquet_file' is not defined
[2025-03-27T06:52:23.074+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T06:52:23.098+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/data_ingestion_gcs_dag.py took 1.134 seconds
[2025-03-27T06:52:53.250+0000] {processor.py:156} INFO - Started process (PID=889) to work on /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T06:52:53.252+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/data_ingestion_gcs_dag.py for tasks to queue
[2025-03-27T06:52:53.253+0000] {logging_mixin.py:117} INFO - [2025-03-27T06:52:53.253+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T06:52:54.463+0000] {logging_mixin.py:117} INFO - [2025-03-27T06:52:54.457+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_gcs_dag.py", line 104, in <module>
    "sourceUris": [f"gs://{BUCKET}/raw/{parquet_file}"],
NameError: name 'parquet_file' is not defined
[2025-03-27T06:52:54.466+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T06:52:54.492+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/data_ingestion_gcs_dag.py took 1.248 seconds
[2025-03-27T06:53:24.743+0000] {processor.py:156} INFO - Started process (PID=905) to work on /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T06:53:24.745+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/data_ingestion_gcs_dag.py for tasks to queue
[2025-03-27T06:53:24.750+0000] {logging_mixin.py:117} INFO - [2025-03-27T06:53:24.748+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T06:53:25.947+0000] {logging_mixin.py:117} INFO - [2025-03-27T06:53:25.940+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_gcs_dag.py", line 104, in <module>
    "sourceUris": [f"gs://{BUCKET}/raw/{parquet_file}"],
NameError: name 'parquet_file' is not defined
[2025-03-27T06:53:25.950+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T06:53:25.992+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/data_ingestion_gcs_dag.py took 1.258 seconds
[2025-03-27T06:53:44.210+0000] {processor.py:156} INFO - Started process (PID=921) to work on /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T06:53:44.213+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/data_ingestion_gcs_dag.py for tasks to queue
[2025-03-27T06:53:44.215+0000] {logging_mixin.py:117} INFO - [2025-03-27T06:53:44.214+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T06:53:45.388+0000] {logging_mixin.py:117} INFO - [2025-03-27T06:53:45.381+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_gcs_dag.py", line 124, in <module>
    download_dataset_task >> format_to_parquet_task >> local_to_gcs_task >> bigquery_external_table_task
NameError: name 'format_to_parquet_task' is not defined
[2025-03-27T06:53:45.391+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T06:53:45.418+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/data_ingestion_gcs_dag.py took 1.216 seconds
[2025-03-27T06:54:06.380+0000] {processor.py:156} INFO - Started process (PID=937) to work on /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T06:54:06.382+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/data_ingestion_gcs_dag.py for tasks to queue
[2025-03-27T06:54:06.383+0000] {logging_mixin.py:117} INFO - [2025-03-27T06:54:06.383+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T06:54:07.501+0000] {processor.py:768} INFO - DAG(s) dict_keys(['data_ingestion_gcs_dag']) retrieved from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T06:54:07.619+0000] {logging_mixin.py:117} INFO - [2025-03-27T06:54:07.619+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2025-03-27T06:54:07.661+0000] {logging_mixin.py:117} INFO - [2025-03-27T06:54:07.660+0000] {dag.py:3324} INFO - Setting next_dagrun for data_ingestion_gcs_dag to 2025-03-26T00:00:00+00:00, run_after=2025-03-27T00:00:00+00:00
[2025-03-27T06:54:07.723+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/data_ingestion_gcs_dag.py took 1.346 seconds
[2025-03-27T06:54:14.857+0000] {processor.py:156} INFO - Started process (PID=939) to work on /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T06:54:14.858+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/data_ingestion_gcs_dag.py for tasks to queue
[2025-03-27T06:54:14.859+0000] {logging_mixin.py:117} INFO - [2025-03-27T06:54:14.859+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T06:54:15.970+0000] {processor.py:768} INFO - DAG(s) dict_keys(['data_ingestion_gcs_dag']) retrieved from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T06:54:15.987+0000] {logging_mixin.py:117} INFO - [2025-03-27T06:54:15.987+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2025-03-27T06:54:16.024+0000] {logging_mixin.py:117} INFO - [2025-03-27T06:54:16.023+0000] {dag.py:3324} INFO - Setting next_dagrun for data_ingestion_gcs_dag to 2025-03-26T00:00:00+00:00, run_after=2025-03-27T00:00:00+00:00
[2025-03-27T06:54:16.086+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/data_ingestion_gcs_dag.py took 1.235 seconds
[2025-03-27T06:54:46.472+0000] {processor.py:156} INFO - Started process (PID=963) to work on /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T06:54:46.474+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/data_ingestion_gcs_dag.py for tasks to queue
[2025-03-27T06:54:46.475+0000] {logging_mixin.py:117} INFO - [2025-03-27T06:54:46.475+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T06:54:47.517+0000] {processor.py:768} INFO - DAG(s) dict_keys(['data_ingestion_gcs_dag']) retrieved from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T06:54:47.560+0000] {logging_mixin.py:117} INFO - [2025-03-27T06:54:47.560+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2025-03-27T06:54:47.598+0000] {logging_mixin.py:117} INFO - [2025-03-27T06:54:47.598+0000] {dag.py:3324} INFO - Setting next_dagrun for data_ingestion_gcs_dag to 2025-03-26T00:00:00+00:00, run_after=2025-03-27T00:00:00+00:00
[2025-03-27T06:54:47.631+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/data_ingestion_gcs_dag.py took 1.164 seconds
[2025-03-27T06:54:54.549+0000] {processor.py:156} INFO - Started process (PID=972) to work on /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T06:54:54.551+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/data_ingestion_gcs_dag.py for tasks to queue
[2025-03-27T06:54:54.553+0000] {logging_mixin.py:117} INFO - [2025-03-27T06:54:54.552+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T06:54:55.775+0000] {processor.py:768} INFO - DAG(s) dict_keys(['data_ingestion_gcs_dag']) retrieved from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T06:54:55.857+0000] {logging_mixin.py:117} INFO - [2025-03-27T06:54:55.857+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2025-03-27T06:54:55.891+0000] {logging_mixin.py:117} INFO - [2025-03-27T06:54:55.891+0000] {dag.py:3324} INFO - Setting next_dagrun for data_ingestion_gcs_dag to 2025-03-26T00:00:00+00:00, run_after=2025-03-27T00:00:00+00:00
[2025-03-27T06:54:55.950+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/data_ingestion_gcs_dag.py took 1.407 seconds
[2025-03-27T06:55:26.043+0000] {processor.py:156} INFO - Started process (PID=988) to work on /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T06:55:26.045+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/data_ingestion_gcs_dag.py for tasks to queue
[2025-03-27T06:55:26.046+0000] {logging_mixin.py:117} INFO - [2025-03-27T06:55:26.046+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T06:55:27.210+0000] {processor.py:768} INFO - DAG(s) dict_keys(['data_ingestion_gcs_dag']) retrieved from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T06:55:27.251+0000] {logging_mixin.py:117} INFO - [2025-03-27T06:55:27.251+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2025-03-27T06:55:27.286+0000] {logging_mixin.py:117} INFO - [2025-03-27T06:55:27.286+0000] {dag.py:3324} INFO - Setting next_dagrun for data_ingestion_gcs_dag to 2025-03-26T00:00:00+00:00, run_after=2025-03-27T00:00:00+00:00
[2025-03-27T06:55:27.333+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/data_ingestion_gcs_dag.py took 1.294 seconds
[2025-03-27T06:55:57.607+0000] {processor.py:156} INFO - Started process (PID=1011) to work on /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T06:55:57.609+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/data_ingestion_gcs_dag.py for tasks to queue
[2025-03-27T06:55:57.610+0000] {logging_mixin.py:117} INFO - [2025-03-27T06:55:57.610+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T06:55:58.701+0000] {processor.py:768} INFO - DAG(s) dict_keys(['data_ingestion_gcs_dag']) retrieved from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T06:55:58.739+0000] {logging_mixin.py:117} INFO - [2025-03-27T06:55:58.739+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2025-03-27T06:55:58.774+0000] {logging_mixin.py:117} INFO - [2025-03-27T06:55:58.774+0000] {dag.py:3324} INFO - Setting next_dagrun for data_ingestion_gcs_dag to 2025-03-26T00:00:00+00:00, run_after=2025-03-27T00:00:00+00:00
[2025-03-27T06:55:58.812+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/data_ingestion_gcs_dag.py took 1.209 seconds
[2025-03-27T06:56:09.765+0000] {processor.py:156} INFO - Started process (PID=1020) to work on /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T06:56:09.767+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/data_ingestion_gcs_dag.py for tasks to queue
[2025-03-27T06:56:09.768+0000] {logging_mixin.py:117} INFO - [2025-03-27T06:56:09.768+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T06:56:10.807+0000] {processor.py:768} INFO - DAG(s) dict_keys(['data_ingestion_gcs_dag']) retrieved from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T06:56:10.883+0000] {logging_mixin.py:117} INFO - [2025-03-27T06:56:10.882+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2025-03-27T06:56:10.921+0000] {logging_mixin.py:117} INFO - [2025-03-27T06:56:10.921+0000] {dag.py:3324} INFO - Setting next_dagrun for data_ingestion_gcs_dag to 2025-03-26T00:00:00+00:00, run_after=2025-03-27T00:00:00+00:00
[2025-03-27T06:56:10.978+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/data_ingestion_gcs_dag.py took 1.218 seconds
[2025-03-27T06:56:41.277+0000] {processor.py:156} INFO - Started process (PID=1043) to work on /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T06:56:41.283+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/data_ingestion_gcs_dag.py for tasks to queue
[2025-03-27T06:56:41.286+0000] {logging_mixin.py:117} INFO - [2025-03-27T06:56:41.285+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T06:56:43.189+0000] {processor.py:768} INFO - DAG(s) dict_keys(['data_ingestion_gcs_dag']) retrieved from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T06:56:43.239+0000] {logging_mixin.py:117} INFO - [2025-03-27T06:56:43.239+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2025-03-27T06:56:43.327+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/data_ingestion_gcs_dag.py took 2.069 seconds
[2025-03-27T06:57:13.595+0000] {processor.py:156} INFO - Started process (PID=1064) to work on /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T06:57:13.597+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/data_ingestion_gcs_dag.py for tasks to queue
[2025-03-27T06:57:13.598+0000] {logging_mixin.py:117} INFO - [2025-03-27T06:57:13.598+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T06:57:14.764+0000] {processor.py:768} INFO - DAG(s) dict_keys(['data_ingestion_gcs_dag']) retrieved from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T06:57:14.806+0000] {logging_mixin.py:117} INFO - [2025-03-27T06:57:14.806+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2025-03-27T06:57:14.900+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/data_ingestion_gcs_dag.py took 1.310 seconds
[2025-03-27T06:57:45.240+0000] {processor.py:156} INFO - Started process (PID=1087) to work on /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T06:57:45.241+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/data_ingestion_gcs_dag.py for tasks to queue
[2025-03-27T06:57:45.242+0000] {logging_mixin.py:117} INFO - [2025-03-27T06:57:45.242+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T06:57:46.406+0000] {processor.py:768} INFO - DAG(s) dict_keys(['data_ingestion_gcs_dag']) retrieved from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T06:57:46.443+0000] {logging_mixin.py:117} INFO - [2025-03-27T06:57:46.442+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2025-03-27T06:57:46.537+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/data_ingestion_gcs_dag.py took 1.302 seconds
[2025-03-27T06:58:16.843+0000] {processor.py:156} INFO - Started process (PID=1110) to work on /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T06:58:16.845+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/data_ingestion_gcs_dag.py for tasks to queue
[2025-03-27T06:58:16.846+0000] {logging_mixin.py:117} INFO - [2025-03-27T06:58:16.846+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T06:58:17.997+0000] {processor.py:768} INFO - DAG(s) dict_keys(['data_ingestion_gcs_dag']) retrieved from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T06:58:18.041+0000] {logging_mixin.py:117} INFO - [2025-03-27T06:58:18.041+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2025-03-27T06:58:18.114+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/data_ingestion_gcs_dag.py took 1.276 seconds
[2025-03-27T06:58:48.435+0000] {processor.py:156} INFO - Started process (PID=1126) to work on /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T06:58:48.437+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/data_ingestion_gcs_dag.py for tasks to queue
[2025-03-27T06:58:48.438+0000] {logging_mixin.py:117} INFO - [2025-03-27T06:58:48.438+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T06:58:49.529+0000] {processor.py:768} INFO - DAG(s) dict_keys(['data_ingestion_gcs_dag']) retrieved from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T06:58:49.574+0000] {logging_mixin.py:117} INFO - [2025-03-27T06:58:49.573+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2025-03-27T06:58:49.647+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/data_ingestion_gcs_dag.py took 1.217 seconds
[2025-03-27T06:59:19.742+0000] {processor.py:156} INFO - Started process (PID=1150) to work on /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T06:59:19.744+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/data_ingestion_gcs_dag.py for tasks to queue
[2025-03-27T06:59:19.745+0000] {logging_mixin.py:117} INFO - [2025-03-27T06:59:19.745+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T06:59:20.955+0000] {processor.py:768} INFO - DAG(s) dict_keys(['data_ingestion_gcs_dag']) retrieved from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T06:59:20.995+0000] {logging_mixin.py:117} INFO - [2025-03-27T06:59:20.994+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2025-03-27T06:59:21.060+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/data_ingestion_gcs_dag.py took 1.323 seconds
[2025-03-27T06:59:51.199+0000] {processor.py:156} INFO - Started process (PID=1165) to work on /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T06:59:51.201+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/data_ingestion_gcs_dag.py for tasks to queue
[2025-03-27T06:59:51.203+0000] {logging_mixin.py:117} INFO - [2025-03-27T06:59:51.202+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T06:59:52.407+0000] {processor.py:768} INFO - DAG(s) dict_keys(['data_ingestion_gcs_dag']) retrieved from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T06:59:52.453+0000] {logging_mixin.py:117} INFO - [2025-03-27T06:59:52.452+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2025-03-27T06:59:52.524+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/data_ingestion_gcs_dag.py took 1.329 seconds
[2025-03-27T07:00:22.640+0000] {processor.py:156} INFO - Started process (PID=1188) to work on /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:00:22.641+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/data_ingestion_gcs_dag.py for tasks to queue
[2025-03-27T07:00:22.643+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:00:22.642+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:00:23.887+0000] {processor.py:768} INFO - DAG(s) dict_keys(['data_ingestion_gcs_dag']) retrieved from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:00:23.927+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:00:23.926+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2025-03-27T07:00:24.009+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/data_ingestion_gcs_dag.py took 1.374 seconds
[2025-03-27T07:00:54.244+0000] {processor.py:156} INFO - Started process (PID=1212) to work on /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:00:54.246+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/data_ingestion_gcs_dag.py for tasks to queue
[2025-03-27T07:00:54.248+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:00:54.248+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:00:55.320+0000] {processor.py:768} INFO - DAG(s) dict_keys(['data_ingestion_gcs_dag']) retrieved from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:00:55.356+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:00:55.355+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2025-03-27T07:00:55.433+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/data_ingestion_gcs_dag.py took 1.195 seconds
[2025-03-27T07:01:25.587+0000] {processor.py:156} INFO - Started process (PID=1228) to work on /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:01:25.589+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/data_ingestion_gcs_dag.py for tasks to queue
[2025-03-27T07:01:25.590+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:01:25.590+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:01:26.736+0000] {processor.py:768} INFO - DAG(s) dict_keys(['data_ingestion_gcs_dag']) retrieved from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:01:26.778+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:01:26.777+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2025-03-27T07:01:26.861+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/data_ingestion_gcs_dag.py took 1.279 seconds
[2025-03-27T07:01:57.032+0000] {processor.py:156} INFO - Started process (PID=1252) to work on /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:01:57.033+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/data_ingestion_gcs_dag.py for tasks to queue
[2025-03-27T07:01:57.051+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:01:57.050+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:01:58.301+0000] {processor.py:768} INFO - DAG(s) dict_keys(['data_ingestion_gcs_dag']) retrieved from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:01:58.341+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:01:58.340+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2025-03-27T07:01:58.432+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/data_ingestion_gcs_dag.py took 1.405 seconds
[2025-03-27T07:02:28.758+0000] {processor.py:156} INFO - Started process (PID=1279) to work on /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:02:28.760+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/data_ingestion_gcs_dag.py for tasks to queue
[2025-03-27T07:02:28.762+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:02:28.762+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:02:30.139+0000] {processor.py:768} INFO - DAG(s) dict_keys(['data_ingestion_gcs_dag']) retrieved from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:02:30.182+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:02:30.182+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2025-03-27T07:02:30.256+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/data_ingestion_gcs_dag.py took 1.506 seconds
[2025-03-27T07:03:00.618+0000] {processor.py:156} INFO - Started process (PID=1296) to work on /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:03:00.620+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/data_ingestion_gcs_dag.py for tasks to queue
[2025-03-27T07:03:00.621+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:03:00.621+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:03:02.077+0000] {processor.py:768} INFO - DAG(s) dict_keys(['data_ingestion_gcs_dag']) retrieved from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:03:02.115+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:03:02.114+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2025-03-27T07:03:02.179+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/data_ingestion_gcs_dag.py took 1.566 seconds
[2025-03-27T07:03:32.306+0000] {processor.py:156} INFO - Started process (PID=1319) to work on /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:03:32.308+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/data_ingestion_gcs_dag.py for tasks to queue
[2025-03-27T07:03:32.309+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:03:32.309+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:03:33.408+0000] {processor.py:768} INFO - DAG(s) dict_keys(['data_ingestion_gcs_dag']) retrieved from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:03:33.466+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:03:33.466+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2025-03-27T07:03:33.560+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/data_ingestion_gcs_dag.py took 1.257 seconds
[2025-03-27T07:04:03.759+0000] {processor.py:156} INFO - Started process (PID=1335) to work on /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:04:03.761+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/data_ingestion_gcs_dag.py for tasks to queue
[2025-03-27T07:04:03.763+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:04:03.763+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:04:05.133+0000] {processor.py:768} INFO - DAG(s) dict_keys(['data_ingestion_gcs_dag']) retrieved from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:04:05.186+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:04:05.185+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2025-03-27T07:04:05.239+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:04:05.238+0000] {dag.py:3324} INFO - Setting next_dagrun for data_ingestion_gcs_dag to 2025-03-27T00:00:00+00:00, run_after=2025-03-28T00:00:00+00:00
[2025-03-27T07:04:05.320+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/data_ingestion_gcs_dag.py took 1.566 seconds
[2025-03-27T07:04:35.668+0000] {processor.py:156} INFO - Started process (PID=1358) to work on /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:04:35.670+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/data_ingestion_gcs_dag.py for tasks to queue
[2025-03-27T07:04:35.671+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:04:35.671+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:04:36.761+0000] {processor.py:768} INFO - DAG(s) dict_keys(['data_ingestion_gcs_dag']) retrieved from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:04:36.799+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:04:36.799+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2025-03-27T07:04:36.833+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:04:36.833+0000] {dag.py:3324} INFO - Setting next_dagrun for data_ingestion_gcs_dag to 2025-03-27T00:00:00+00:00, run_after=2025-03-28T00:00:00+00:00
[2025-03-27T07:04:36.877+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/data_ingestion_gcs_dag.py took 1.217 seconds
[2025-03-27T07:05:07.178+0000] {processor.py:156} INFO - Started process (PID=1380) to work on /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:05:07.180+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/data_ingestion_gcs_dag.py for tasks to queue
[2025-03-27T07:05:07.181+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:05:07.181+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:05:08.306+0000] {processor.py:768} INFO - DAG(s) dict_keys(['data_ingestion_gcs_dag']) retrieved from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:05:08.350+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:05:08.349+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2025-03-27T07:05:08.389+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:05:08.389+0000] {dag.py:3324} INFO - Setting next_dagrun for data_ingestion_gcs_dag to 2025-03-27T00:00:00+00:00, run_after=2025-03-28T00:00:00+00:00
[2025-03-27T07:05:08.420+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/data_ingestion_gcs_dag.py took 1.247 seconds
[2025-03-27T07:05:38.696+0000] {processor.py:156} INFO - Started process (PID=1399) to work on /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:05:38.698+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/data_ingestion_gcs_dag.py for tasks to queue
[2025-03-27T07:05:38.699+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:05:38.699+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:05:39.781+0000] {processor.py:768} INFO - DAG(s) dict_keys(['data_ingestion_gcs_dag']) retrieved from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:05:39.821+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:05:39.821+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2025-03-27T07:05:39.904+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/data_ingestion_gcs_dag.py took 1.216 seconds
[2025-03-27T07:06:10.228+0000] {processor.py:156} INFO - Started process (PID=1422) to work on /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:06:10.231+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/data_ingestion_gcs_dag.py for tasks to queue
[2025-03-27T07:06:10.233+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:06:10.232+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:06:11.461+0000] {processor.py:768} INFO - DAG(s) dict_keys(['data_ingestion_gcs_dag']) retrieved from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:06:11.504+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:06:11.503+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2025-03-27T07:06:11.598+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/data_ingestion_gcs_dag.py took 1.378 seconds
[2025-03-27T07:06:41.935+0000] {processor.py:156} INFO - Started process (PID=1445) to work on /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:06:41.937+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/data_ingestion_gcs_dag.py for tasks to queue
[2025-03-27T07:06:41.939+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:06:41.939+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:06:42.994+0000] {processor.py:768} INFO - DAG(s) dict_keys(['data_ingestion_gcs_dag']) retrieved from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:06:43.032+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:06:43.032+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2025-03-27T07:06:43.131+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/data_ingestion_gcs_dag.py took 1.203 seconds
[2025-03-27T07:07:13.206+0000] {processor.py:156} INFO - Started process (PID=1461) to work on /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:07:13.208+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/data_ingestion_gcs_dag.py for tasks to queue
[2025-03-27T07:07:13.210+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:07:13.209+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:07:14.308+0000] {processor.py:768} INFO - DAG(s) dict_keys(['data_ingestion_gcs_dag']) retrieved from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:07:14.343+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:07:14.343+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2025-03-27T07:07:14.401+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/data_ingestion_gcs_dag.py took 1.199 seconds
[2025-03-27T07:07:44.706+0000] {processor.py:156} INFO - Started process (PID=1484) to work on /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:07:44.708+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/data_ingestion_gcs_dag.py for tasks to queue
[2025-03-27T07:07:44.709+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:07:44.709+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:07:45.748+0000] {processor.py:768} INFO - DAG(s) dict_keys(['data_ingestion_gcs_dag']) retrieved from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:07:45.788+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:07:45.787+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2025-03-27T07:07:45.860+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/data_ingestion_gcs_dag.py took 1.158 seconds
[2025-03-27T07:07:55.013+0000] {processor.py:156} INFO - Started process (PID=1493) to work on /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:07:55.015+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/data_ingestion_gcs_dag.py for tasks to queue
[2025-03-27T07:07:55.016+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:07:55.016+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:07:56.011+0000] {processor.py:768} INFO - DAG(s) dict_keys(['data_ingestion_gcs_dag']) retrieved from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:07:56.107+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:07:56.107+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2025-03-27T07:07:56.181+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/data_ingestion_gcs_dag.py took 1.172 seconds
[2025-03-27T07:07:58.042+0000] {processor.py:156} INFO - Started process (PID=1495) to work on /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:07:58.043+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/data_ingestion_gcs_dag.py for tasks to queue
[2025-03-27T07:07:58.045+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:07:58.045+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:07:59.145+0000] {processor.py:768} INFO - DAG(s) dict_keys(['data_ingestion_gcs_dag']) retrieved from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:07:59.164+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:07:59.163+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2025-03-27T07:07:59.256+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/data_ingestion_gcs_dag.py took 1.219 seconds
[2025-03-27T07:08:29.517+0000] {processor.py:156} INFO - Started process (PID=1522) to work on /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:08:29.519+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/data_ingestion_gcs_dag.py for tasks to queue
[2025-03-27T07:08:29.520+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:08:29.519+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:08:30.717+0000] {processor.py:768} INFO - DAG(s) dict_keys(['data_ingestion_gcs_dag']) retrieved from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:08:30.804+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:08:30.803+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2025-03-27T07:08:30.869+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/data_ingestion_gcs_dag.py took 1.357 seconds
[2025-03-27T07:09:01.215+0000] {processor.py:156} INFO - Started process (PID=1538) to work on /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:09:01.216+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/data_ingestion_gcs_dag.py for tasks to queue
[2025-03-27T07:09:01.218+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:09:01.218+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:09:02.505+0000] {processor.py:768} INFO - DAG(s) dict_keys(['data_ingestion_gcs_dag']) retrieved from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:09:02.549+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:09:02.549+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2025-03-27T07:09:02.633+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/data_ingestion_gcs_dag.py took 1.423 seconds
[2025-03-27T07:09:32.964+0000] {processor.py:156} INFO - Started process (PID=1561) to work on /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:09:32.965+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/data_ingestion_gcs_dag.py for tasks to queue
[2025-03-27T07:09:32.967+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:09:32.966+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:09:34.038+0000] {processor.py:768} INFO - DAG(s) dict_keys(['data_ingestion_gcs_dag']) retrieved from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:09:34.078+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:09:34.077+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2025-03-27T07:09:34.145+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/data_ingestion_gcs_dag.py took 1.186 seconds
[2025-03-27T07:10:04.327+0000] {processor.py:156} INFO - Started process (PID=1584) to work on /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:10:04.329+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/data_ingestion_gcs_dag.py for tasks to queue
[2025-03-27T07:10:04.331+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:10:04.330+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:10:05.599+0000] {processor.py:768} INFO - DAG(s) dict_keys(['data_ingestion_gcs_dag']) retrieved from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:10:05.649+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:10:05.649+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2025-03-27T07:10:05.751+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/data_ingestion_gcs_dag.py took 1.430 seconds
[2025-03-27T07:10:36.099+0000] {processor.py:156} INFO - Started process (PID=1600) to work on /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:10:36.101+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/data_ingestion_gcs_dag.py for tasks to queue
[2025-03-27T07:10:36.103+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:10:36.102+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:10:37.259+0000] {processor.py:768} INFO - DAG(s) dict_keys(['data_ingestion_gcs_dag']) retrieved from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:10:37.299+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:10:37.299+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2025-03-27T07:10:37.364+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/data_ingestion_gcs_dag.py took 1.271 seconds
[2025-03-27T07:11:07.678+0000] {processor.py:156} INFO - Started process (PID=1623) to work on /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:11:07.680+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/data_ingestion_gcs_dag.py for tasks to queue
[2025-03-27T07:11:07.681+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:11:07.681+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:11:08.817+0000] {processor.py:768} INFO - DAG(s) dict_keys(['data_ingestion_gcs_dag']) retrieved from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:11:08.859+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:11:08.858+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2025-03-27T07:11:08.944+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/data_ingestion_gcs_dag.py took 1.271 seconds
[2025-03-27T07:11:39.248+0000] {processor.py:156} INFO - Started process (PID=1639) to work on /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:11:39.250+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/data_ingestion_gcs_dag.py for tasks to queue
[2025-03-27T07:11:39.251+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:11:39.251+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:11:40.676+0000] {processor.py:768} INFO - DAG(s) dict_keys(['data_ingestion_gcs_dag']) retrieved from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:11:40.716+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:11:40.715+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2025-03-27T07:11:40.803+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/data_ingestion_gcs_dag.py took 1.563 seconds
[2025-03-27T07:12:11.131+0000] {processor.py:156} INFO - Started process (PID=1662) to work on /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:12:11.133+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/data_ingestion_gcs_dag.py for tasks to queue
[2025-03-27T07:12:11.134+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:12:11.134+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:12:12.387+0000] {processor.py:768} INFO - DAG(s) dict_keys(['data_ingestion_gcs_dag']) retrieved from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:12:12.436+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:12:12.435+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2025-03-27T07:12:12.500+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/data_ingestion_gcs_dag.py took 1.374 seconds
[2025-03-27T07:12:42.784+0000] {processor.py:156} INFO - Started process (PID=1685) to work on /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:12:42.786+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/data_ingestion_gcs_dag.py for tasks to queue
[2025-03-27T07:12:42.787+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:12:42.787+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:12:43.900+0000] {processor.py:768} INFO - DAG(s) dict_keys(['data_ingestion_gcs_dag']) retrieved from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:12:43.939+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:12:43.938+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2025-03-27T07:12:44.014+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/data_ingestion_gcs_dag.py took 1.234 seconds
[2025-03-27T07:13:14.157+0000] {processor.py:156} INFO - Started process (PID=1701) to work on /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:13:14.159+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/data_ingestion_gcs_dag.py for tasks to queue
[2025-03-27T07:13:14.161+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:13:14.161+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:13:15.419+0000] {processor.py:768} INFO - DAG(s) dict_keys(['data_ingestion_gcs_dag']) retrieved from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:13:15.457+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:13:15.457+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2025-03-27T07:13:15.547+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/data_ingestion_gcs_dag.py took 1.404 seconds
[2025-03-27T07:13:45.835+0000] {processor.py:156} INFO - Started process (PID=1724) to work on /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:13:45.837+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/data_ingestion_gcs_dag.py for tasks to queue
[2025-03-27T07:13:45.838+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:13:45.838+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:13:47.002+0000] {processor.py:768} INFO - DAG(s) dict_keys(['data_ingestion_gcs_dag']) retrieved from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:13:47.066+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:13:47.066+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2025-03-27T07:13:47.126+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:13:47.125+0000] {dag.py:3324} INFO - Setting next_dagrun for data_ingestion_gcs_dag to 2025-03-27T00:00:00+00:00, run_after=2025-03-28T00:00:00+00:00
[2025-03-27T07:13:47.173+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/data_ingestion_gcs_dag.py took 1.342 seconds
[2025-03-27T07:14:17.510+0000] {processor.py:156} INFO - Started process (PID=1747) to work on /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:14:17.512+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/data_ingestion_gcs_dag.py for tasks to queue
[2025-03-27T07:14:17.514+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:14:17.513+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:14:18.686+0000] {processor.py:768} INFO - DAG(s) dict_keys(['data_ingestion_gcs_dag']) retrieved from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:14:18.724+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:14:18.723+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2025-03-27T07:14:18.767+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:14:18.767+0000] {dag.py:3324} INFO - Setting next_dagrun for data_ingestion_gcs_dag to 2025-03-27T00:00:00+00:00, run_after=2025-03-28T00:00:00+00:00
[2025-03-27T07:14:18.815+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/data_ingestion_gcs_dag.py took 1.312 seconds
[2025-03-27T07:14:49.137+0000] {processor.py:156} INFO - Started process (PID=1763) to work on /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:14:49.139+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/data_ingestion_gcs_dag.py for tasks to queue
[2025-03-27T07:14:49.140+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:14:49.140+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:14:50.286+0000] {processor.py:768} INFO - DAG(s) dict_keys(['data_ingestion_gcs_dag']) retrieved from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:14:50.335+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:14:50.333+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2025-03-27T07:14:50.386+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:14:50.386+0000] {dag.py:3324} INFO - Setting next_dagrun for data_ingestion_gcs_dag to 2025-03-27T00:00:00+00:00, run_after=2025-03-28T00:00:00+00:00
[2025-03-27T07:14:50.440+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/data_ingestion_gcs_dag.py took 1.309 seconds
[2025-03-27T07:15:20.759+0000] {processor.py:156} INFO - Started process (PID=1786) to work on /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:15:20.764+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/data_ingestion_gcs_dag.py for tasks to queue
[2025-03-27T07:15:20.766+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:15:20.766+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:15:22.057+0000] {processor.py:768} INFO - DAG(s) dict_keys(['data_ingestion_gcs_dag']) retrieved from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:15:22.121+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:15:22.120+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2025-03-27T07:15:22.175+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:15:22.175+0000] {dag.py:3324} INFO - Setting next_dagrun for data_ingestion_gcs_dag to 2025-03-27T00:00:00+00:00, run_after=2025-03-28T00:00:00+00:00
[2025-03-27T07:15:22.228+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/data_ingestion_gcs_dag.py took 1.476 seconds
[2025-03-27T07:15:52.537+0000] {processor.py:156} INFO - Started process (PID=1810) to work on /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:15:52.539+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/data_ingestion_gcs_dag.py for tasks to queue
[2025-03-27T07:15:52.541+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:15:52.541+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:15:53.742+0000] {processor.py:768} INFO - DAG(s) dict_keys(['data_ingestion_gcs_dag']) retrieved from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:15:53.786+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:15:53.785+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2025-03-27T07:15:53.838+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:15:53.838+0000] {dag.py:3324} INFO - Setting next_dagrun for data_ingestion_gcs_dag to 2025-03-27T00:00:00+00:00, run_after=2025-03-28T00:00:00+00:00
[2025-03-27T07:15:53.919+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/data_ingestion_gcs_dag.py took 1.389 seconds
[2025-03-27T07:16:23.800+0000] {processor.py:156} INFO - Started process (PID=1826) to work on /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:16:23.801+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/data_ingestion_gcs_dag.py for tasks to queue
[2025-03-27T07:16:23.803+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:16:23.802+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:16:24.933+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:16:24.925+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_gcs_dag.py", line 73, in <module>
    create_empty_dataset_task = BigQueryCreateEmptyDatasetOperator(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 408, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 1346, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 408, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 755, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to BigQueryCreateEmptyDatasetOperator (task_id: create_empty_dataset_task). Invalid arguments were:
**kwargs: {'datasetid': 'tate_data_all'}
[2025-03-27T07:16:24.934+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:16:24.963+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/data_ingestion_gcs_dag.py took 1.167 seconds
[2025-03-27T07:16:55.066+0000] {processor.py:156} INFO - Started process (PID=1849) to work on /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:16:55.068+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/data_ingestion_gcs_dag.py for tasks to queue
[2025-03-27T07:16:55.069+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:16:55.069+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:16:56.406+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:16:56.397+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_gcs_dag.py", line 73, in <module>
    create_empty_dataset_task = BigQueryCreateEmptyDatasetOperator(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 408, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 1346, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 408, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 755, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to BigQueryCreateEmptyDatasetOperator (task_id: create_empty_dataset_task). Invalid arguments were:
**kwargs: {'datasetid': 'tate_data_all'}
[2025-03-27T07:16:56.407+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:16:56.433+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/data_ingestion_gcs_dag.py took 1.371 seconds
[2025-03-27T07:17:26.552+0000] {processor.py:156} INFO - Started process (PID=1865) to work on /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:17:26.554+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/data_ingestion_gcs_dag.py for tasks to queue
[2025-03-27T07:17:26.555+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:17:26.555+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:17:27.600+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:17:27.593+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_gcs_dag.py", line 73, in <module>
    create_empty_dataset_task = BigQueryCreateEmptyDatasetOperator(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 408, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 1346, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 408, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 755, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to BigQueryCreateEmptyDatasetOperator (task_id: create_empty_dataset_task). Invalid arguments were:
**kwargs: {'datasetid': 'tate_data_all'}
[2025-03-27T07:17:27.601+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:17:27.641+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/data_ingestion_gcs_dag.py took 1.093 seconds
[2025-03-27T07:17:49.811+0000] {processor.py:156} INFO - Started process (PID=1881) to work on /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:17:49.813+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/data_ingestion_gcs_dag.py for tasks to queue
[2025-03-27T07:17:49.814+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:17:49.814+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:17:51.375+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:17:51.362+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_gcs_dag.py", line 72, in <module>
    create_empty_dataset_task = BigQueryCreateEmptyDatasetOperator(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 408, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 1346, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 408, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 755, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to BigQueryCreateEmptyDatasetOperator (task_id: create_empty_dataset_task). Invalid arguments were:
**kwargs: {'datasetid': 'tate_data_all'}
[2025-03-27T07:17:51.376+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:17:51.429+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/data_ingestion_gcs_dag.py took 1.624 seconds
[2025-03-27T07:18:07.004+0000] {processor.py:156} INFO - Started process (PID=1897) to work on /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:18:07.006+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/data_ingestion_gcs_dag.py for tasks to queue
[2025-03-27T07:18:07.007+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:18:07.007+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:18:07.960+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:18:07.953+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_gcs_dag.py", line 72, in <module>
    create_empty_dataset_task = BigQueryCreateEmptyDatasetOperator(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 408, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 1346, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 408, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 755, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to BigQueryCreateEmptyDatasetOperator (task_id: create_empty_dataset_task). Invalid arguments were:
**kwargs: {'datasetid': 'tate_data_all'}
[2025-03-27T07:18:07.962+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:18:08.000+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/data_ingestion_gcs_dag.py took 1.000 seconds
[2025-03-27T07:18:38.298+0000] {processor.py:156} INFO - Started process (PID=1913) to work on /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:18:38.300+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/data_ingestion_gcs_dag.py for tasks to queue
[2025-03-27T07:18:38.301+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:18:38.301+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:18:39.523+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:18:39.513+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_gcs_dag.py", line 72, in <module>
    create_empty_dataset_task = BigQueryCreateEmptyDatasetOperator(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 408, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 1346, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 408, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 755, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to BigQueryCreateEmptyDatasetOperator (task_id: create_empty_dataset_task). Invalid arguments were:
**kwargs: {'datasetid': 'tate_data_all'}
[2025-03-27T07:18:39.525+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:18:39.552+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/data_ingestion_gcs_dag.py took 1.260 seconds
[2025-03-27T07:19:09.901+0000] {processor.py:156} INFO - Started process (PID=1937) to work on /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:19:09.902+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/data_ingestion_gcs_dag.py for tasks to queue
[2025-03-27T07:19:09.904+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:19:09.903+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:19:11.065+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:19:11.055+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_gcs_dag.py", line 72, in <module>
    create_empty_dataset_task = BigQueryCreateEmptyDatasetOperator(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 408, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 1346, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 408, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 755, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to BigQueryCreateEmptyDatasetOperator (task_id: create_empty_dataset_task). Invalid arguments were:
**kwargs: {'datasetid': 'tate_data_all'}
[2025-03-27T07:19:11.066+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:19:11.114+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/data_ingestion_gcs_dag.py took 1.218 seconds
[2025-03-27T07:19:41.200+0000] {processor.py:156} INFO - Started process (PID=1960) to work on /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:19:41.202+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/data_ingestion_gcs_dag.py for tasks to queue
[2025-03-27T07:19:41.203+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:19:41.203+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:19:42.376+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:19:42.367+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_gcs_dag.py", line 72, in <module>
    create_empty_dataset_task = BigQueryCreateEmptyDatasetOperator(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 408, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 1346, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 408, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 755, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to BigQueryCreateEmptyDatasetOperator (task_id: create_empty_dataset_task). Invalid arguments were:
**kwargs: {'datasetid': 'tate_data_all'}
[2025-03-27T07:19:42.377+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:19:42.423+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/data_ingestion_gcs_dag.py took 1.227 seconds
[2025-03-27T07:20:07.709+0000] {processor.py:156} INFO - Started process (PID=1976) to work on /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:20:07.711+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/data_ingestion_gcs_dag.py for tasks to queue
[2025-03-27T07:20:07.712+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:20:07.712+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:20:08.758+0000] {processor.py:768} INFO - DAG(s) dict_keys(['data_ingestion_gcs_dag']) retrieved from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:20:08.846+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:20:08.846+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2025-03-27T07:20:08.882+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:20:08.882+0000] {dag.py:3324} INFO - Setting next_dagrun for data_ingestion_gcs_dag to 2025-03-27T00:00:00+00:00, run_after=2025-03-28T00:00:00+00:00
[2025-03-27T07:20:08.923+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/data_ingestion_gcs_dag.py took 1.217 seconds
[2025-03-27T07:20:39.033+0000] {processor.py:156} INFO - Started process (PID=1997) to work on /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:20:39.036+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/data_ingestion_gcs_dag.py for tasks to queue
[2025-03-27T07:20:39.037+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:20:39.037+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:20:40.884+0000] {processor.py:768} INFO - DAG(s) dict_keys(['data_ingestion_gcs_dag']) retrieved from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:20:40.931+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:20:40.930+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2025-03-27T07:20:41.016+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/data_ingestion_gcs_dag.py took 1.993 seconds
[2025-03-27T07:21:11.304+0000] {processor.py:156} INFO - Started process (PID=2021) to work on /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:21:11.305+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/data_ingestion_gcs_dag.py for tasks to queue
[2025-03-27T07:21:11.307+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:21:11.307+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:21:12.325+0000] {processor.py:768} INFO - DAG(s) dict_keys(['data_ingestion_gcs_dag']) retrieved from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:21:12.386+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:21:12.385+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2025-03-27T07:21:12.496+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/data_ingestion_gcs_dag.py took 1.196 seconds
[2025-03-27T07:21:42.591+0000] {processor.py:156} INFO - Started process (PID=2044) to work on /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:21:42.593+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/data_ingestion_gcs_dag.py for tasks to queue
[2025-03-27T07:21:42.594+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:21:42.594+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:21:43.642+0000] {processor.py:768} INFO - DAG(s) dict_keys(['data_ingestion_gcs_dag']) retrieved from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:21:43.683+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:21:43.683+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2025-03-27T07:21:43.765+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/data_ingestion_gcs_dag.py took 1.179 seconds
[2025-03-27T07:22:14.114+0000] {processor.py:156} INFO - Started process (PID=2060) to work on /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:22:14.116+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/data_ingestion_gcs_dag.py for tasks to queue
[2025-03-27T07:22:14.117+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:22:14.117+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:22:15.330+0000] {processor.py:768} INFO - DAG(s) dict_keys(['data_ingestion_gcs_dag']) retrieved from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:22:15.369+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:22:15.368+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2025-03-27T07:22:15.427+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:22:15.427+0000] {dag.py:3324} INFO - Setting next_dagrun for data_ingestion_gcs_dag to 2025-03-27T00:00:00+00:00, run_after=2025-03-28T00:00:00+00:00
[2025-03-27T07:22:15.461+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/data_ingestion_gcs_dag.py took 1.351 seconds
[2025-03-27T07:22:45.779+0000] {processor.py:156} INFO - Started process (PID=2083) to work on /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:22:45.781+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/data_ingestion_gcs_dag.py for tasks to queue
[2025-03-27T07:22:45.782+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:22:45.782+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:22:47.028+0000] {processor.py:768} INFO - DAG(s) dict_keys(['data_ingestion_gcs_dag']) retrieved from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:22:47.073+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:22:47.071+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2025-03-27T07:22:47.115+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:22:47.115+0000] {dag.py:3324} INFO - Setting next_dagrun for data_ingestion_gcs_dag to 2025-03-27T00:00:00+00:00, run_after=2025-03-28T00:00:00+00:00
[2025-03-27T07:22:47.162+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/data_ingestion_gcs_dag.py took 1.387 seconds
[2025-03-27T07:23:17.487+0000] {processor.py:156} INFO - Started process (PID=2106) to work on /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:23:17.489+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/data_ingestion_gcs_dag.py for tasks to queue
[2025-03-27T07:23:17.490+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:23:17.490+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:23:18.554+0000] {processor.py:768} INFO - DAG(s) dict_keys(['data_ingestion_gcs_dag']) retrieved from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:23:18.595+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:23:18.594+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2025-03-27T07:23:18.636+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:23:18.636+0000] {dag.py:3324} INFO - Setting next_dagrun for data_ingestion_gcs_dag to 2025-03-27T00:00:00+00:00, run_after=2025-03-28T00:00:00+00:00
[2025-03-27T07:23:18.682+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/data_ingestion_gcs_dag.py took 1.201 seconds
[2025-03-27T07:23:48.762+0000] {processor.py:156} INFO - Started process (PID=2122) to work on /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:23:48.764+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/data_ingestion_gcs_dag.py for tasks to queue
[2025-03-27T07:23:48.766+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:23:48.765+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:23:50.004+0000] {processor.py:768} INFO - DAG(s) dict_keys(['data_ingestion_gcs_dag']) retrieved from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:23:50.045+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:23:50.044+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2025-03-27T07:23:50.086+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:23:50.086+0000] {dag.py:3324} INFO - Setting next_dagrun for data_ingestion_gcs_dag to 2025-03-27T00:00:00+00:00, run_after=2025-03-28T00:00:00+00:00
[2025-03-27T07:23:50.119+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/data_ingestion_gcs_dag.py took 1.361 seconds
[2025-03-27T07:24:20.321+0000] {processor.py:156} INFO - Started process (PID=2145) to work on /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:24:20.323+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/data_ingestion_gcs_dag.py for tasks to queue
[2025-03-27T07:24:20.324+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:24:20.324+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:24:21.449+0000] {processor.py:768} INFO - DAG(s) dict_keys(['data_ingestion_gcs_dag']) retrieved from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:24:21.491+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:24:21.491+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2025-03-27T07:24:21.529+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:24:21.529+0000] {dag.py:3324} INFO - Setting next_dagrun for data_ingestion_gcs_dag to 2025-03-27T00:00:00+00:00, run_after=2025-03-28T00:00:00+00:00
[2025-03-27T07:24:21.578+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/data_ingestion_gcs_dag.py took 1.264 seconds
[2025-03-27T07:24:51.713+0000] {processor.py:156} INFO - Started process (PID=2161) to work on /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:24:51.714+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/data_ingestion_gcs_dag.py for tasks to queue
[2025-03-27T07:24:51.716+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:24:51.716+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:24:53.171+0000] {processor.py:768} INFO - DAG(s) dict_keys(['data_ingestion_gcs_dag']) retrieved from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:24:53.224+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:24:53.224+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2025-03-27T07:24:53.275+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:24:53.275+0000] {dag.py:3324} INFO - Setting next_dagrun for data_ingestion_gcs_dag to 2025-03-27T00:00:00+00:00, run_after=2025-03-28T00:00:00+00:00
[2025-03-27T07:24:53.313+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/data_ingestion_gcs_dag.py took 1.606 seconds
[2025-03-27T07:25:23.672+0000] {processor.py:156} INFO - Started process (PID=2184) to work on /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:25:23.673+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/data_ingestion_gcs_dag.py for tasks to queue
[2025-03-27T07:25:23.674+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:25:23.674+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:25:24.889+0000] {processor.py:768} INFO - DAG(s) dict_keys(['data_ingestion_gcs_dag']) retrieved from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:25:24.930+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:25:24.929+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2025-03-27T07:25:24.977+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:25:24.976+0000] {dag.py:3324} INFO - Setting next_dagrun for data_ingestion_gcs_dag to 2025-03-27T00:00:00+00:00, run_after=2025-03-28T00:00:00+00:00
[2025-03-27T07:25:25.025+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/data_ingestion_gcs_dag.py took 1.358 seconds
[2025-03-27T07:25:55.400+0000] {processor.py:156} INFO - Started process (PID=2207) to work on /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:25:55.402+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/data_ingestion_gcs_dag.py for tasks to queue
[2025-03-27T07:25:55.403+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:25:55.403+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:25:56.597+0000] {processor.py:768} INFO - DAG(s) dict_keys(['data_ingestion_gcs_dag']) retrieved from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:25:56.645+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:25:56.644+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2025-03-27T07:25:56.685+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:25:56.684+0000] {dag.py:3324} INFO - Setting next_dagrun for data_ingestion_gcs_dag to 2025-03-27T00:00:00+00:00, run_after=2025-03-28T00:00:00+00:00
[2025-03-27T07:25:56.737+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/data_ingestion_gcs_dag.py took 1.343 seconds
[2025-03-27T07:26:27.068+0000] {processor.py:156} INFO - Started process (PID=2223) to work on /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:26:27.069+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/data_ingestion_gcs_dag.py for tasks to queue
[2025-03-27T07:26:27.071+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:26:27.071+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:26:28.291+0000] {processor.py:768} INFO - DAG(s) dict_keys(['data_ingestion_gcs_dag']) retrieved from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:26:28.332+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:26:28.331+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2025-03-27T07:26:28.371+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:26:28.371+0000] {dag.py:3324} INFO - Setting next_dagrun for data_ingestion_gcs_dag to 2025-03-27T00:00:00+00:00, run_after=2025-03-28T00:00:00+00:00
[2025-03-27T07:26:28.405+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/data_ingestion_gcs_dag.py took 1.342 seconds
[2025-03-27T07:26:58.756+0000] {processor.py:156} INFO - Started process (PID=2247) to work on /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:26:58.758+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/data_ingestion_gcs_dag.py for tasks to queue
[2025-03-27T07:26:58.760+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:26:58.759+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:27:00.065+0000] {processor.py:768} INFO - DAG(s) dict_keys(['data_ingestion_gcs_dag']) retrieved from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:27:00.107+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:27:00.106+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2025-03-27T07:27:00.143+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:27:00.143+0000] {dag.py:3324} INFO - Setting next_dagrun for data_ingestion_gcs_dag to 2025-03-27T00:00:00+00:00, run_after=2025-03-28T00:00:00+00:00
[2025-03-27T07:27:00.190+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/data_ingestion_gcs_dag.py took 1.440 seconds
[2025-03-27T07:27:30.520+0000] {processor.py:156} INFO - Started process (PID=2270) to work on /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:27:30.521+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/data_ingestion_gcs_dag.py for tasks to queue
[2025-03-27T07:27:30.523+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:27:30.523+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:27:31.558+0000] {processor.py:768} INFO - DAG(s) dict_keys(['data_ingestion_gcs_dag']) retrieved from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:27:31.598+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:27:31.598+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2025-03-27T07:27:31.632+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:27:31.632+0000] {dag.py:3324} INFO - Setting next_dagrun for data_ingestion_gcs_dag to 2025-03-27T00:00:00+00:00, run_after=2025-03-28T00:00:00+00:00
[2025-03-27T07:27:31.684+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/data_ingestion_gcs_dag.py took 1.171 seconds
[2025-03-27T07:27:50.715+0000] {processor.py:156} INFO - Started process (PID=2279) to work on /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:27:50.717+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/data_ingestion_gcs_dag.py for tasks to queue
[2025-03-27T07:27:50.718+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:27:50.718+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:27:52.104+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:27:52.096+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_gcs_dag.py", line 101, in <module>
    bigquery_external_table_task1 = BigQueryCreateExternalTableOperator(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 408, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 1101, in __init__
    raise ValueError("You provided both `table_resource` and exclusive keywords arguments.")
ValueError: You provided both `table_resource` and exclusive keywords arguments.
[2025-03-27T07:27:52.105+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:27:52.147+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/data_ingestion_gcs_dag.py took 1.438 seconds
[2025-03-27T07:28:22.456+0000] {processor.py:156} INFO - Started process (PID=2302) to work on /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:28:22.458+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/data_ingestion_gcs_dag.py for tasks to queue
[2025-03-27T07:28:22.459+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:28:22.459+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:28:23.987+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:28:23.978+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_gcs_dag.py", line 101, in <module>
    bigquery_external_table_task1 = BigQueryCreateExternalTableOperator(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 408, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 1101, in __init__
    raise ValueError("You provided both `table_resource` and exclusive keywords arguments.")
ValueError: You provided both `table_resource` and exclusive keywords arguments.
[2025-03-27T07:28:23.988+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:28:24.028+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/data_ingestion_gcs_dag.py took 1.578 seconds
[2025-03-27T07:28:54.363+0000] {processor.py:156} INFO - Started process (PID=2325) to work on /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:28:54.364+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/data_ingestion_gcs_dag.py for tasks to queue
[2025-03-27T07:28:54.366+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:28:54.366+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:28:55.534+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:28:55.523+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_gcs_dag.py", line 101, in <module>
    bigquery_external_table_task1 = BigQueryCreateExternalTableOperator(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 408, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 1101, in __init__
    raise ValueError("You provided both `table_resource` and exclusive keywords arguments.")
ValueError: You provided both `table_resource` and exclusive keywords arguments.
[2025-03-27T07:28:55.535+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:28:55.564+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/data_ingestion_gcs_dag.py took 1.206 seconds
[2025-03-27T07:29:20.587+0000] {processor.py:156} INFO - Started process (PID=2341) to work on /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:29:20.588+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/data_ingestion_gcs_dag.py for tasks to queue
[2025-03-27T07:29:20.589+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:29:20.589+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:29:21.796+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:29:21.787+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_gcs_dag.py", line 101, in <module>
    bigquery_external_table_task1 = BigQueryCreateExternalTableOperator(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 408, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 1101, in __init__
    raise ValueError("You provided both `table_resource` and exclusive keywords arguments.")
ValueError: You provided both `table_resource` and exclusive keywords arguments.
[2025-03-27T07:29:21.798+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:29:21.839+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/data_ingestion_gcs_dag.py took 1.257 seconds
[2025-03-27T07:29:52.111+0000] {processor.py:156} INFO - Started process (PID=2357) to work on /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:29:52.112+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/data_ingestion_gcs_dag.py for tasks to queue
[2025-03-27T07:29:52.114+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:29:52.114+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:29:53.583+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:29:53.572+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_gcs_dag.py", line 101, in <module>
    bigquery_external_table_task1 = BigQueryCreateExternalTableOperator(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 408, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 1101, in __init__
    raise ValueError("You provided both `table_resource` and exclusive keywords arguments.")
ValueError: You provided both `table_resource` and exclusive keywords arguments.
[2025-03-27T07:29:53.585+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:29:53.630+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/data_ingestion_gcs_dag.py took 1.525 seconds
[2025-03-27T07:30:23.946+0000] {processor.py:156} INFO - Started process (PID=2381) to work on /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:30:23.947+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/data_ingestion_gcs_dag.py for tasks to queue
[2025-03-27T07:30:23.948+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:30:23.948+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:30:25.003+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:30:24.994+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_gcs_dag.py", line 101, in <module>
    bigquery_external_table_task1 = BigQueryCreateExternalTableOperator(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 408, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 1101, in __init__
    raise ValueError("You provided both `table_resource` and exclusive keywords arguments.")
ValueError: You provided both `table_resource` and exclusive keywords arguments.
[2025-03-27T07:30:25.004+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:30:25.043+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/data_ingestion_gcs_dag.py took 1.102 seconds
[2025-03-27T07:30:55.229+0000] {processor.py:156} INFO - Started process (PID=2404) to work on /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:30:55.231+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/data_ingestion_gcs_dag.py for tasks to queue
[2025-03-27T07:30:55.232+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:30:55.232+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:30:56.320+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:30:56.311+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_gcs_dag.py", line 101, in <module>
    bigquery_external_table_task1 = BigQueryCreateExternalTableOperator(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 408, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 1101, in __init__
    raise ValueError("You provided both `table_resource` and exclusive keywords arguments.")
ValueError: You provided both `table_resource` and exclusive keywords arguments.
[2025-03-27T07:30:56.321+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:30:56.361+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/data_ingestion_gcs_dag.py took 1.136 seconds
[2025-03-27T07:31:26.674+0000] {processor.py:156} INFO - Started process (PID=2420) to work on /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:31:26.676+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/data_ingestion_gcs_dag.py for tasks to queue
[2025-03-27T07:31:26.677+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:31:26.677+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:31:27.795+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:31:27.786+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_gcs_dag.py", line 101, in <module>
    bigquery_external_table_task1 = BigQueryCreateExternalTableOperator(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 408, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 1101, in __init__
    raise ValueError("You provided both `table_resource` and exclusive keywords arguments.")
ValueError: You provided both `table_resource` and exclusive keywords arguments.
[2025-03-27T07:31:27.796+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:31:27.837+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/data_ingestion_gcs_dag.py took 1.168 seconds
[2025-03-27T07:31:57.978+0000] {processor.py:156} INFO - Started process (PID=2443) to work on /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:31:57.979+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/data_ingestion_gcs_dag.py for tasks to queue
[2025-03-27T07:31:57.981+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:31:57.980+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:31:59.080+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:31:59.068+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_gcs_dag.py", line 101, in <module>
    bigquery_external_table_task1 = BigQueryCreateExternalTableOperator(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 408, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 1101, in __init__
    raise ValueError("You provided both `table_resource` and exclusive keywords arguments.")
ValueError: You provided both `table_resource` and exclusive keywords arguments.
[2025-03-27T07:31:59.081+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:31:59.123+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/data_ingestion_gcs_dag.py took 1.150 seconds
[2025-03-27T07:32:07.250+0000] {processor.py:156} INFO - Started process (PID=2452) to work on /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:32:07.252+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/data_ingestion_gcs_dag.py for tasks to queue
[2025-03-27T07:32:07.254+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:32:07.254+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:32:08.439+0000] {processor.py:768} INFO - DAG(s) dict_keys(['data_ingestion_gcs_dag']) retrieved from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:32:08.530+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:32:08.530+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2025-03-27T07:32:08.569+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:32:08.568+0000] {dag.py:3324} INFO - Setting next_dagrun for data_ingestion_gcs_dag to 2025-03-27T00:00:00+00:00, run_after=2025-03-28T00:00:00+00:00
[2025-03-27T07:32:08.631+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/data_ingestion_gcs_dag.py took 1.386 seconds
[2025-03-27T07:32:38.986+0000] {processor.py:156} INFO - Started process (PID=2473) to work on /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:32:38.988+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/data_ingestion_gcs_dag.py for tasks to queue
[2025-03-27T07:32:38.990+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:32:38.989+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:32:40.128+0000] {processor.py:768} INFO - DAG(s) dict_keys(['data_ingestion_gcs_dag']) retrieved from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:32:40.171+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:32:40.170+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2025-03-27T07:32:40.238+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/data_ingestion_gcs_dag.py took 1.260 seconds
[2025-03-27T07:33:00.168+0000] {processor.py:156} INFO - Started process (PID=2489) to work on /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:33:00.170+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/data_ingestion_gcs_dag.py for tasks to queue
[2025-03-27T07:33:00.171+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:33:00.171+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:33:01.574+0000] {processor.py:768} INFO - DAG(s) dict_keys(['data_ingestion_gcs_dag']) retrieved from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2025-03-27T07:33:01.615+0000] {logging_mixin.py:117} INFO - [2025-03-27T07:33:01.614+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2025-03-27T07:33:01.701+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/data_ingestion_gcs_dag.py took 1.537 seconds
