[0m23:47:15.826815 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000257A49328D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000257A70DDB20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000257A4023560>]}


============================== 23:47:15.835020 | 04ac7f4d-1573-4eb3-895a-bc91e7fba4e2 ==============================
[0m23:47:15.835020 [info ] [MainThread]: Running with dbt=1.9.3
[0m23:47:15.836481 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'profiles_dir': 'C:\\Users\\lidu0\\.dbt', 'log_path': 'logs', 'version_check': 'True', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt clean', 'log_format': 'default', 'static_parser': 'True', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m23:47:15.837480 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\lidu0\OneDrive\Ê°åÈù¢\Classes\data-engineering-zoomcamp\tate_art_project\dbt\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m23:47:15.839542 [debug] [MainThread]: Command `dbt clean` failed at 23:47:15.839233 after 0.16 seconds
[0m23:47:15.839542 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000257A75625A0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000257A6842DE0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000257A73AE600>]}
[0m23:47:15.839542 [debug] [MainThread]: Flushing usage events
[0m23:47:16.329275 [debug] [MainThread]: An error was encountered while trying to flush usage events
